### ISSUE TITLE
integrate with Canavs publishing functionality 

### ISSUE THREAD

**Issue by ShannonRice** [Harvard-ATG/hxat#84]
(Submitted by Caitlin Rajagopalan of Poetry in America)
Also in Jira as ANNO-134 https://jira.huit.harvard.edu/browse/ANNO-134
It would be great if the annotation tool emulated the published/unpublished categorization of the rest of the Canvas content.  (That is to say, if Week 3 of content is not yet visible to students, it would be ideal if we could schedule Week 3 annotations in the AnnotationsX tab to become visible when the rest of the week opens to students.)  Currently, students can access future weeks' annotations, even though the surrounding content of those weeks is not visible to them.  We see that there's a way to unpublish annotations in the AnnotationsX tab manually, but it seems a bit clunky to re-publish manually slightly in advance of launch each week (in case, for instance, I missed re-publishing one, and students couldn't access it until someone notified us of the issue).

**Comment by arthurian** [comment]
This could be accomplished by isolating assignments so that students can't navigate to other assignments within the context of a Canvas module. The tool wouldn't need to be aware of Canvas's published/unpublished module state, simply whether or not the tool is loading an assignment directly or not and whether the user is a student or not. 

Since this may be desirable behavior in Canvas, and not in edX, we could add a course-level setting that determines how this should work.
